name: Convert .py to .tns

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
    - name: Clone luna
      run: git clone https://github.com/ndless-nspire/Luna.git
    - name: Build luna
      run: make
      working-directory: ./Luna
    - name: Create output directory
      run: mkdir tns_files
    - name: Convert .py to .tns
      run: ./Luna/luna main.py tns_files/DigiCod_Nspire.tns
    - name: Upload .tns artifact
      uses: actions/upload-artifact@v4
      with:
        name: tns-files
        path: tns_files/
