name: Run MicroPython Tests

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  micropython-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libffi-dev pkg-config

    - name: Build MicroPython Unix port
      run: |
        git clone https://github.com/micropython/micropython.git
        cd micropython/ports/unix
        make submodules
        make
        echo "MICROPYTHON=$(pwd)/build-standard/micropython" >> $GITHUB_ENV

    - name: Run test.py with MicroPython
      run: |
        $MICROPYTHON test.py
