name: Run MicroPython Tests

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  micropython-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libffi-dev pkg-config

    - name: Build MicroPython Unix port
      run: |
        git clone https://github.com/micropython/micropython.git
        cd micropython
        git submodule update --init lib/mp-readline lib/libffi lib/timeutils
        make -C mpy-cross
        make -C ports/unix
        echo "MICROPYTHON=$(pwd)/ports/unix/micropython" >> $GITHUB_ENV

    - name: Run test.py with MicroPython
      run: |
        $MICROPYTHON test.py
